baseurl: "https://sdqali.in"
title: "{code that works}"
layoutdir: "layouts"
contentdir: "content"
publishdir: "public"
taxonomies:
    category: "categories"
    tag: "tags"
    series: "series"
permalinks:
    blog: /blog/:year/:month/:day/:title/
metadataformat: "yaml"
params:
  description: "My posts with working code - tested and verified - and actionable explanations for specific programming problems."
  author: "Sadique Ali"
  keywords:
    - Programming
    - Software Development
    - Java Development
    - Coding
  googleAnalytics: "UA-86967633-1"
PygmentsCodeFences: true
pygmentsstyle: "manni"
enableRobotsTXT: true
